### PR TITLE
Update: Symlink ordering

### PR DESCRIPTION
**Pull request by daniel-schier**
- Resolves: #5

### CODE REVIEW

**Review by Cinux90 — APPROVED** [review]
Looks not like ansible ^^, but ok from my side.

**Comment by daniel-schier** [comment]
@fiete201 @Cinux90 @donvipre would be awesome, if you can approve :)

**Review by Cinux90 — APPROVED** [review]
i have selected the approval.. no idea why it's not triggered...
secound try...

EDIT:
Ok also here no success. Maybe i'm not authorized to approve it? ^^'

**Comment by daniel-schier** [comment]
@Cinux90 that may be possible. have to have a look and will force the merge for now

**Pull request merged**
